# -*- coding: utf-8 -*-
"""Ejercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zru6eXcDp05Wcyipsgyr5jHv9sF8ZSm_
"""

import numpy as np
import random

arregloA = np.array([0]*100)

for i in range(100):
  arregloA[i] = random.randint(0,500)

print("1.- El arreglo es: ", arregloA, "\n")

print("2.- Los valores de los índices pares son: ", arregloA[::2], "\n")

print("3.- El elemento mayor es: ", max(arregloA), "\n")

indiceMaximo = np.where(arregloA == max(arregloA))
print("4.- El índice del elemento mayor es: ", indiceMaximo[0], "\n")

print("5.- El elemento menor es: ", min(arregloA), "\n")

arregloA2 = arregloA[:].copy()
print("6.- La copia del arreglo por 3 es: ", (arregloA2 * 3), "\n")

print("7.- La suma del segundo arreglo es: ", sum(arregloA2), "\n")

print("8.- El promedio del segundo arreglo es: ", (sum(arregloA2)/len(arregloA2)), "\n")